- hosts: all
  become: true
  tasks:
    - name: Clone "nvm" repository
      become_user: vagrant
      git:
        repo: https://github.com/creationix/nvm.git
        dest: ~/.nvm
        version: v0.33.8

    - name: Install "nvm"
      become_user: vagrant
      shell: ~/.nvm/install.sh

    - name: Install "node"
      become_user: vagrant
      shell: . ~/.nvm/nvm.sh && nvm install node
      args:
        executable: /bin/bash

    - name: Update "npm"
      become_user: vagrant
      shell: . ~/.nvm/nvm.sh && npm install npm -g
      args:
        executable: /bin/bash

    - name: Install global npm package "nodemon"
      become_user: vagrant
      shell: . ~/.nvm/nvm.sh && npm install nodemon -g
      args:
        executable: /bin/bash

    - name: Install global npm package "create-react-app"
      become_user: vagrant
      shell: . ~/.nvm/nvm.sh && npm install create-react-app -g
      args:
        executable: /bin/bash

    - name: Install global npm package "serve"
      become_user: vagrant
      shell: . ~/.nvm/nvm.sh && npm install serve -g
      args:
        executable: /bin/bash

    - name: Install global npm package "firebase-tools"
      become_user: vagrant
      shell: . ~/.nvm/nvm.sh && npm install firebase-tools -g
      args:
        executable: /bin/bash

    - name: Install global npm package "heroku-cli"
      become_user: vagrant
      shell: . ~/.nvm/nvm.sh && npm install heroku-cli -g
      args:
        executable: /bin/bash

    - name: Install "postgresql"
      apt:
        name: postgresql
        state: present

    - name: Install "postgresql-contrib"
      apt:
        name: postgresql-contrib
        state: present

    - name: Install "cmake"
      apt:
        name: cmake
        state: present

    - name: Install "g++/gcc"
      apt:
        name: g++
        state: present

    - name: Install "tree"
      apt:
        name: tree
        state: present

    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
