- hosts: all
  become: true
  tasks:
    # - name: Cloning "nvm" repository
    #   become_user: vagrant
    #   git:
    #     repo: https://github.com/creationix/nvm.git
    #     dest: ~/.nvm
    #     version: v0.33.8

    # - name: Installing "nvm"
    #   become_user: vagrant
    #   shell: ~/.nvm/install.sh

    # - name: Installing "node"
    #   become_user: vagrant
    #   shell: . ~/.nvm/nvm.sh && nvm install node
    #   args:
    #     executable: /bin/bash

    # - name: Installing global npm package "firebase-tools"
    #   become_user: vagrant
    #   shell: . ~/.nvm/nvm.sh && npm install firebase-tools -g
    #   args:
    #     executable: /bin/bash

    # - name: Installing global npm package "heroku-cli"
    #   become_user: vagrant
    #   shell: . ~/.nvm/nvm.sh && npm install heroku-cli -g
    #   args:
    #     executable: /bin/bash

    - name: Installing "postgresql"
      apt:
        name: postgresql
        state: present

    - name: Installing "postgresql-contrib"
      apt:
        name: postgresql-contrib
        state: present

    - name: Configuring "postgresql"
      script: /vagrant/scripts/configure_postgres.sh

    - name: Adding repository for latest "gcc/g++"
      apt_repository:
        repo: ppa:ubuntu-toolchain-r/test
        state: present

    - name: Installing "gcc/g++"
      apt:
        name: g++-7
        state: present

    - name: Updating system version of "gcc/g++"
      shell: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7

    - name: Adding repository for latest "cmake"
      apt_repository:
        repo: ppa:nschloe/cmake-nightly
        state: present

    - name: Installing "cmake"
      apt:
        name: cmake
        state: present

    - name: Installing "tree"
      apt:
        name: tree
        state: present

    - name: Updating packages to their latest version
      apt:
        upgrade: dist

    - name: Removing useless packages from the cache
      apt:
        autoclean: yes

    - name: Removing dependencies that are no longer required
      apt:
        autoremove: yes
