- hosts: all
  become: yes
  tasks:
    - name: Install "nodejs"
      shell: |
        curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
        sudo apt install nodejs -y
        sudo npm update -g

    - name: Install global npm package "create-react-app"
      shell: sudo npm install create-react-app -g

    - name: Install global npm package "serve"
      shell: sudo npm install serve -g

    - name: Install "cmake"
      apt:
        name: cmake
        state: present

    - name: Install "g++/gcc"
      apt:
        name: g++
        state: present

    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
